#!/bin/bash

# This allows you to run new files at the highest level against phpstan

# ensure we have the latest master
git fetch --force origin "master"

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
NEW_FILES=$(git diff --color --name-only --diff-filter=A origin/master $CURRENT_BRANCH | grep ".php")
PHAR="vendor/bin/phpstan.phar"

if [ -f bin/phpstan.phar ]; then
    PHAR="bin/phpstan.phar"
fi

COMMAND="$PHAR analyse -c phpstan.neon -l 7 "
NEEDS_TO_RUN=0

if [ "$CURRENT_BRANCH" == "master" ]
then
    exit 0
fi

while read -r FILE; do
    echo $FILE

    if [ -n "$FILE" ]
    then
        NEEDS_TO_RUN=1
        COMMAND="$COMMAND \"$FILE\" "
    fi
done <<< "$NEW_FILES"

if [ $NEEDS_TO_RUN -eq 1 ]
then
    eval $COMMAND
fi
